spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: cosmin
    password: password
    driverClassName: org.postgresql.Driver

